In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [ ]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [ ]:
import tensorflow as tf


In [7]:
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [8]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [11]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=ct.fit_transform(x)

In [13]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=1)

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
train_x=sc.fit_transform(train_x)
test_x=sc.fit_transform(test_x)


In [24]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#ouput_layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
ann.fit(train_x,train_y,batch_size=32,epochs=500)

Epoch 1/500
250/250 [==============================] - 0s 983us/step - loss: 0.5443 - accuracy: 0.7966
Epoch 2/500
250/250 [==============================] - 0s 924us/step - loss: 0.4844 - accuracy: 0.7972
Epoch 3/500
250/250 [==============================] - 0s 897us/step - loss: 0.4589 - accuracy: 0.7972
Epoch 4/500
250/250 [==============================] - 0s 906us/step - loss: 0.4434 - accuracy: 0.7972
Epoch 5/500
250/250 [==============================] - 0s 926us/step - loss: 0.4323 - accuracy: 0.8004
Epoch 6/500
250/250 [==============================] - 0s 963us/step - loss: 0.4241 - accuracy: 0.8150
Epoch 7/500
250/250 [==============================] - 0s 902us/step - loss: 0.4172 - accuracy: 0.8257
Epoch 8/500
250/250 [==============================] - 0s 891us/step - loss: 0.4118 - accuracy: 0.8271
Epoch 9/500
250/250 [==============================] - 0s 902us/step - loss: 0.4070 - accuracy: 0.8295
Epoch 10/500
250/250 [==============================] - 0s 891us/step - l

In [25]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

array([[False]])

In [26]:
pred_y=ann.predict(test_x)
pred_y=pred_y>0.5
#np.set_printoptions(precision=2)
#print(np.concatenate((pred_y.reshape(len(pred_y),1),test_y.reshape(len(test_y),1)),1))
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_m=confusion_matrix(test_y,pred_y)
print(confusion_m)
accuracy_score(test_y,pred_y)

[[1526   59]
 [ 199  216]]


0.871